apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations: null
  labels:
    app.kubernetes.io/name: kurrentdb-operator
  name: kurrentdb-license
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kurrentdb-license
subjects:
  - kind: ServiceAccount
    name: kurrentdb-operator
