apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations: null
  labels: null
  name: kurrentdb-license
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
